version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    commit-message:
      prefix: chore
      include: scope
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    commit-message:
      prefix: chore
      include: scope
    open-pull-requests-limit: 5
    groups:
      cargo-minor-patch:
        update-types:
          - minor
          - patch
